### ISSUE TITLE
Memtest program couldn't allocate more than 120KB for  arr[]  (test with DE1-SOC board)

### ISSUE THREAD

**Issue by jackzhang1992** [MIPSfpga/mipsfpga-plus#26]
hi, today I tested the 04_memtest program with DE1-SOC board.  (this time sdrams works, which I am sure of.)

I noticed the program couldn't allocate more  than 120KB for arr[ ](program failed means only the LEDR[0] is on after program is exected). 

Only when TEST_ARRISIZE is set less than 30*1024, the program could work successfully( success means LEDR[4] is on, after the program is executed.)

```
    #define TEST_ARRSIZE    (30*1024)    /* Size = sizeof(uint32_t)*30K = 120KB*/
    #define TEST_DELAY      1000000
    #define TEST_COUNT      0xff
```

So now my conclusion is that:
-   sdram could work in my DE1-SOC board.
-   But it seems the mfp_system couldn't access to the full 64MB memory of my sdram chip, which is exactly as same as the one in DE10-Lite board.

How can it be? and are there any clues for me to solve this problem?

Thank you for your help.

**Comment by zhelnio** [comment]
@jackzhang1992 I have met this before. It could be because of some timing problems with SDRAM. When memory access works, but not for all the address space. Does https://github.com/zhelnio/ahb_lite_sdram works on this board?

**Comment by jackzhang1992** [comment]
@zhelnio  yes,  I made https://github.com/zhelnio/ahb_lite_sdram works on this board.  After that, then I am thinking of continuing to test the mipsfpga plus project.

**Comment by jackzhang1992** [comment]
@zhelnio 
I tested the **ahb_lite_sdram** to access more address space, I found 
 **ahb_lite_sdram**  could access to 60MB with my current params.

the test params I used in **ahb_lite_sdram** project is as follows:
```
	ahb_lite_rw_master
    #(
        .ADDR_INCREMENT ( 4         ),
        .DELAY_BITS     ( 20        ),
        .INCREMENT_CNT  ( 15728640     ),
        .READ_ITER_CNT  ( 10   )
    )
    master 
    (
        .HCLK       (   HCLK       ),
    .....
```


that means this project could access to 
0x00+4*15728640 =0x3c0 0000 =60MB  space.
And the project could run successfully on my fpga board.

So now, I am very confused about how to set the timing params suitable for mipsfpga plus project.
